#项目名
spring:
      # DataSource Config
  # 新版本为com.mysql.cj.jdbc.Driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.69.69:3306/partner
    username: xinhuo
    password: xinhuoLove.
  # session失效时间
  session:
    timeout: 86400
    store-type: redis
  redis:
    host: 117.72.69.69
    port: 6379
    database: 1
    password: abcde
server:
  address: 0.0.0.0









