#项目名
spring:
      # DataSource Config
  # 新版本为com.mysql.cj.jdbc.Driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1:3306/partner
    username: xinhuo
    password: 1
  # session失效时间
  session:
    timeout: 86400
    store-type: redis
  redis:
    host: 1
    port: 6379
    database: 1
    password: 1
server:
  address: 0.0.0.0









